### ISSUE TITLE
Escape/encode and Unescape/decode queries properly

### ISSUE THREAD

**Issue by makew0rld** [pgorman/gneto#1]
Gemini does queries slightly differently than Go's stdlib can provide. Use these funcs instead, which are included in [go-gemini](https://github.com/makeworld-the-better-one/go-gemini) and the [other go-gemini](https://sr.ht/~adnano/go-gemini/).

```go
// QueryEscape provides URL query escaping in a way that follows the Gemini spec.
// It is the same as url.PathEscape, but it also replaces the +, because Gemini
// requires percent-escaping for queries.
func QueryEscape(query string) string {
    return strings.ReplaceAll(url.PathEscape(query), "+", "%2B")
}

// QueryUnescape is the same as url.PathUnescape
func QueryUnescape(query string) (string, error) {
    return url.PathUnescape(query)
}
```

The reason this is required is because Gemini does not allow pluses to be used for spaces in queries. They always represent a literal plus sign.

**Comment by pgorman** [comment]
Thanks! As you point out, section 1.2 of the Gemini spec says: "Spaces in gemini URIs should be encoded as %20, not +." And, consequently, a literal "+" should be escaped as "%2B".

This is fixed in commit 4b9017c.
